# https://github.com/charliermarsh/ruff
# https://beta.ruff.rs/docs/
# https://beta.ruff.rs/docs/rules/#rules

[tool.ruff]

# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.12.2
target-version = "py312"

[tool.ruff.lint]
extend-select = [
    "C4",
    "SIM",
    "TCH",
    "I"
]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
